jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - docker/check
      - docker/build:
          image: goodmoney/protoc
      - docker/push:
          digest-path: /tmp/digest.txt
          image: goodmoney/protoc
          tag: latest
orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
