jobs:
  build-and-push:
    machine:
      docker_layer_caching: true
      resource_class: large

    steps:
      - checkout
      - docker/check
      - docker/build:
          image: goodmoney/protoc
      - docker/push:
          digest-path: /tmp/digest.txt
          image: goodmoney/protoc
orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
