name: Docker Image

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: goodmoney/docker-protobuf/protoc
        tag_with_ref: true      
